name: Deploy to Amplify

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change to your required Node.js version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
           aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
           aws-region: us-east-1

      - name: Install AWS Amplify CLI
        run: npm install -g @aws-amplify/cli
             echo $PATH
             amplify init --yes
             amplify --version
             
      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Debug Environment Variables
        run: |
          echo "ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Deploy to Amplify
        env:
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SDK_LOAD_CONFIG: 1  # Add this line
